condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 60
normalize_comments = true
reorder_impl_items = true
spaces_around_ranges = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
